// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DeclarativeSourceDefinition extends pulumi.CustomResource {
    /**
     * Get an existing DeclarativeSourceDefinition resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DeclarativeSourceDefinitionState, opts?: pulumi.CustomResourceOptions): DeclarativeSourceDefinition {
        return new DeclarativeSourceDefinition(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'airbyte:index/declarativeSourceDefinition:DeclarativeSourceDefinition';

    /**
     * Returns true if the given object is an instance of DeclarativeSourceDefinition.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DeclarativeSourceDefinition {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DeclarativeSourceDefinition.__pulumiType;
    }

    /**
     * Low code CDK manifest JSON object. Parsed as JSON.
     */
    public readonly manifest!: pulumi.Output<string>;
    /**
     * Requires replacement if changed.
     */
    public readonly name!: pulumi.Output<string>;
    public /*out*/ readonly version!: pulumi.Output<number>;
    public readonly workspaceId!: pulumi.Output<string>;

    /**
     * Create a DeclarativeSourceDefinition resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DeclarativeSourceDefinitionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DeclarativeSourceDefinitionArgs | DeclarativeSourceDefinitionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DeclarativeSourceDefinitionState | undefined;
            resourceInputs["manifest"] = state ? state.manifest : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
            resourceInputs["workspaceId"] = state ? state.workspaceId : undefined;
        } else {
            const args = argsOrState as DeclarativeSourceDefinitionArgs | undefined;
            if ((!args || args.manifest === undefined) && !opts.urn) {
                throw new Error("Missing required property 'manifest'");
            }
            if ((!args || args.workspaceId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'workspaceId'");
            }
            resourceInputs["manifest"] = args ? args.manifest : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["workspaceId"] = args ? args.workspaceId : undefined;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DeclarativeSourceDefinition.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering DeclarativeSourceDefinition resources.
 */
export interface DeclarativeSourceDefinitionState {
    /**
     * Low code CDK manifest JSON object. Parsed as JSON.
     */
    manifest?: pulumi.Input<string>;
    /**
     * Requires replacement if changed.
     */
    name?: pulumi.Input<string>;
    version?: pulumi.Input<number>;
    workspaceId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DeclarativeSourceDefinition resource.
 */
export interface DeclarativeSourceDefinitionArgs {
    /**
     * Low code CDK manifest JSON object. Parsed as JSON.
     */
    manifest: pulumi.Input<string>;
    /**
     * Requires replacement if changed.
     */
    name?: pulumi.Input<string>;
    workspaceId: pulumi.Input<string>;
}
