// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDestinationPgvector(args: GetDestinationPgvectorArgs, opts?: pulumi.InvokeOptions): Promise<GetDestinationPgvectorResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getDestinationPgvector:getDestinationPgvector", {
        "destinationId": args.destinationId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDestinationPgvector.
 */
export interface GetDestinationPgvectorArgs {
    destinationId: string;
}

/**
 * A collection of values returned by getDestinationPgvector.
 */
export interface GetDestinationPgvectorResult {
    readonly configuration: string;
    readonly destinationId: string;
    readonly destinationType: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly workspaceId: string;
}
export function getDestinationPgvectorOutput(args: GetDestinationPgvectorOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDestinationPgvectorResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getDestinationPgvector:getDestinationPgvector", {
        "destinationId": args.destinationId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDestinationPgvector.
 */
export interface GetDestinationPgvectorOutputArgs {
    destinationId: pulumi.Input<string>;
}
