// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDestinationAstra(args: GetDestinationAstraArgs, opts?: pulumi.InvokeOptions): Promise<GetDestinationAstraResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getDestinationAstra:getDestinationAstra", {
        "destinationId": args.destinationId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDestinationAstra.
 */
export interface GetDestinationAstraArgs {
    destinationId: string;
}

/**
 * A collection of values returned by getDestinationAstra.
 */
export interface GetDestinationAstraResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    readonly destinationId: string;
    readonly destinationType: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetDestinationAstraResourceAllocation;
    readonly workspaceId: string;
}
export function getDestinationAstraOutput(args: GetDestinationAstraOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDestinationAstraResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getDestinationAstra:getDestinationAstra", {
        "destinationId": args.destinationId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDestinationAstra.
 */
export interface GetDestinationAstraOutputArgs {
    destinationId: pulumi.Input<string>;
}
