// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceKatana(args: GetSourceKatanaArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceKatanaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceKatana:getSourceKatana", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceKatana.
 */
export interface GetSourceKatanaArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceKatana.
 */
export interface GetSourceKatanaResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceKatanaResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceKatanaOutput(args: GetSourceKatanaOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceKatanaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceKatana:getSourceKatana", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceKatana.
 */
export interface GetSourceKatanaOutputArgs {
    sourceId: pulumi.Input<string>;
}
