// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceLessAnnoyingCrm(args: GetSourceLessAnnoyingCrmArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceLessAnnoyingCrmResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceLessAnnoyingCrm:getSourceLessAnnoyingCrm", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceLessAnnoyingCrm.
 */
export interface GetSourceLessAnnoyingCrmArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceLessAnnoyingCrm.
 */
export interface GetSourceLessAnnoyingCrmResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceLessAnnoyingCrmResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceLessAnnoyingCrmOutput(args: GetSourceLessAnnoyingCrmOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceLessAnnoyingCrmResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceLessAnnoyingCrm:getSourceLessAnnoyingCrm", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceLessAnnoyingCrm.
 */
export interface GetSourceLessAnnoyingCrmOutputArgs {
    sourceId: pulumi.Input<string>;
}
