// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceShipstation(args: GetSourceShipstationArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceShipstationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceShipstation:getSourceShipstation", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceShipstation.
 */
export interface GetSourceShipstationArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceShipstation.
 */
export interface GetSourceShipstationResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceShipstationResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceShipstationOutput(args: GetSourceShipstationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceShipstationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceShipstation:getSourceShipstation", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceShipstation.
 */
export interface GetSourceShipstationOutputArgs {
    sourceId: pulumi.Input<string>;
}
