// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceChameleon(args: GetSourceChameleonArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceChameleonResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceChameleon:getSourceChameleon", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceChameleon.
 */
export interface GetSourceChameleonArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceChameleon.
 */
export interface GetSourceChameleonResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceChameleonResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceChameleonOutput(args: GetSourceChameleonOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceChameleonResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceChameleon:getSourceChameleon", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceChameleon.
 */
export interface GetSourceChameleonOutputArgs {
    sourceId: pulumi.Input<string>;
}
