// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceOracleEnterprise(args: GetSourceOracleEnterpriseArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceOracleEnterpriseResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceOracleEnterprise:getSourceOracleEnterprise", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceOracleEnterprise.
 */
export interface GetSourceOracleEnterpriseArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceOracleEnterprise.
 */
export interface GetSourceOracleEnterpriseResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceOracleEnterpriseResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceOracleEnterpriseOutput(args: GetSourceOracleEnterpriseOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceOracleEnterpriseResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceOracleEnterprise:getSourceOracleEnterprise", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceOracleEnterprise.
 */
export interface GetSourceOracleEnterpriseOutputArgs {
    sourceId: pulumi.Input<string>;
}
