// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceCareQualityCommission(args: GetSourceCareQualityCommissionArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceCareQualityCommissionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceCareQualityCommission:getSourceCareQualityCommission", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCareQualityCommission.
 */
export interface GetSourceCareQualityCommissionArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceCareQualityCommission.
 */
export interface GetSourceCareQualityCommissionResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceCareQualityCommissionResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceCareQualityCommissionOutput(args: GetSourceCareQualityCommissionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceCareQualityCommissionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceCareQualityCommission:getSourceCareQualityCommission", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCareQualityCommission.
 */
export interface GetSourceCareQualityCommissionOutputArgs {
    sourceId: pulumi.Input<string>;
}
