// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceBigmailer(args: GetSourceBigmailerArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceBigmailerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceBigmailer:getSourceBigmailer", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBigmailer.
 */
export interface GetSourceBigmailerArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceBigmailer.
 */
export interface GetSourceBigmailerResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceBigmailerResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceBigmailerOutput(args: GetSourceBigmailerOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceBigmailerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceBigmailer:getSourceBigmailer", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBigmailer.
 */
export interface GetSourceBigmailerOutputArgs {
    sourceId: pulumi.Input<string>;
}
