// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSourceAppfigures(args: GetSourceAppfiguresArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceAppfiguresResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceAppfigures:getSourceAppfigures", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceAppfigures.
 */
export interface GetSourceAppfiguresArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceAppfigures.
 */
export interface GetSourceAppfiguresResult {
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceAppfiguresOutput(args: GetSourceAppfiguresOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceAppfiguresResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceAppfigures:getSourceAppfigures", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceAppfigures.
 */
export interface GetSourceAppfiguresOutputArgs {
    sourceId: pulumi.Input<string>;
}
