// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourcePartnerize(args: GetSourcePartnerizeArgs, opts?: pulumi.InvokeOptions): Promise<GetSourcePartnerizeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourcePartnerize:getSourcePartnerize", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePartnerize.
 */
export interface GetSourcePartnerizeArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourcePartnerize.
 */
export interface GetSourcePartnerizeResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourcePartnerizeResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourcePartnerizeOutput(args: GetSourcePartnerizeOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourcePartnerizeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourcePartnerize:getSourcePartnerize", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePartnerize.
 */
export interface GetSourcePartnerizeOutputArgs {
    sourceId: pulumi.Input<string>;
}
