// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceMailosaur(args: GetSourceMailosaurArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceMailosaurResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceMailosaur:getSourceMailosaur", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceMailosaur.
 */
export interface GetSourceMailosaurArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceMailosaur.
 */
export interface GetSourceMailosaurResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceMailosaurResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceMailosaurOutput(args: GetSourceMailosaurOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceMailosaurResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceMailosaur:getSourceMailosaur", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceMailosaur.
 */
export interface GetSourceMailosaurOutputArgs {
    sourceId: pulumi.Input<string>;
}
