// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourcePardot(args: GetSourcePardotArgs, opts?: pulumi.InvokeOptions): Promise<GetSourcePardotResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourcePardot:getSourcePardot", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePardot.
 */
export interface GetSourcePardotArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourcePardot.
 */
export interface GetSourcePardotResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourcePardotResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourcePardotOutput(args: GetSourcePardotOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourcePardotResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourcePardot:getSourcePardot", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePardot.
 */
export interface GetSourcePardotOutputArgs {
    sourceId: pulumi.Input<string>;
}
