// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourcePexelsApi(args: GetSourcePexelsApiArgs, opts?: pulumi.InvokeOptions): Promise<GetSourcePexelsApiResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourcePexelsApi:getSourcePexelsApi", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePexelsApi.
 */
export interface GetSourcePexelsApiArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourcePexelsApi.
 */
export interface GetSourcePexelsApiResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourcePexelsApiResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourcePexelsApiOutput(args: GetSourcePexelsApiOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourcePexelsApiResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourcePexelsApi:getSourcePexelsApi", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePexelsApi.
 */
export interface GetSourcePexelsApiOutputArgs {
    sourceId: pulumi.Input<string>;
}
