// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceSmartwaiver(args: GetSourceSmartwaiverArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSmartwaiverResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSmartwaiver:getSourceSmartwaiver", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSmartwaiver.
 */
export interface GetSourceSmartwaiverArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSmartwaiver.
 */
export interface GetSourceSmartwaiverResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceSmartwaiverResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceSmartwaiverOutput(args: GetSourceSmartwaiverOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceSmartwaiverResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceSmartwaiver:getSourceSmartwaiver", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSmartwaiver.
 */
export interface GetSourceSmartwaiverOutputArgs {
    sourceId: pulumi.Input<string>;
}
