// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceKeka(args: GetSourceKekaArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceKekaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceKeka:getSourceKeka", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceKeka.
 */
export interface GetSourceKekaArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceKeka.
 */
export interface GetSourceKekaResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceKekaResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceKekaOutput(args: GetSourceKekaOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceKekaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceKeka:getSourceKeka", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceKeka.
 */
export interface GetSourceKekaOutputArgs {
    sourceId: pulumi.Input<string>;
}
