// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSourceCalendly(args: GetSourceCalendlyArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceCalendlyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceCalendly:getSourceCalendly", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCalendly.
 */
export interface GetSourceCalendlyArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceCalendly.
 */
export interface GetSourceCalendlyResult {
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceCalendlyOutput(args: GetSourceCalendlyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceCalendlyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceCalendly:getSourceCalendly", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCalendly.
 */
export interface GetSourceCalendlyOutputArgs {
    sourceId: pulumi.Input<string>;
}
