// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceGreenhouse(args: GetSourceGreenhouseArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceGreenhouseResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceGreenhouse:getSourceGreenhouse", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGreenhouse.
 */
export interface GetSourceGreenhouseArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceGreenhouse.
 */
export interface GetSourceGreenhouseResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceGreenhouseResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceGreenhouseOutput(args: GetSourceGreenhouseOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceGreenhouseResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceGreenhouse:getSourceGreenhouse", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGreenhouse.
 */
export interface GetSourceGreenhouseOutputArgs {
    sourceId: pulumi.Input<string>;
}
