// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSourceJotform(args: GetSourceJotformArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceJotformResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceJotform:getSourceJotform", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceJotform.
 */
export interface GetSourceJotformArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceJotform.
 */
export interface GetSourceJotformResult {
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceJotformOutput(args: GetSourceJotformOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceJotformResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceJotform:getSourceJotform", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceJotform.
 */
export interface GetSourceJotformOutputArgs {
    sourceId: pulumi.Input<string>;
}
