// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceAppcues(args: GetSourceAppcuesArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceAppcuesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceAppcues:getSourceAppcues", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceAppcues.
 */
export interface GetSourceAppcuesArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceAppcues.
 */
export interface GetSourceAppcuesResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceAppcuesResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceAppcuesOutput(args: GetSourceAppcuesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceAppcuesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceAppcues:getSourceAppcues", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceAppcues.
 */
export interface GetSourceAppcuesOutputArgs {
    sourceId: pulumi.Input<string>;
}
