// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceGoldcast(args: GetSourceGoldcastArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceGoldcastResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceGoldcast:getSourceGoldcast", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGoldcast.
 */
export interface GetSourceGoldcastArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceGoldcast.
 */
export interface GetSourceGoldcastResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceGoldcastResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceGoldcastOutput(args: GetSourceGoldcastOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceGoldcastResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceGoldcast:getSourceGoldcast", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGoldcast.
 */
export interface GetSourceGoldcastOutputArgs {
    sourceId: pulumi.Input<string>;
}
