// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceZohoDesk(args: GetSourceZohoDeskArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceZohoDeskResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceZohoDesk:getSourceZohoDesk", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceZohoDesk.
 */
export interface GetSourceZohoDeskArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceZohoDesk.
 */
export interface GetSourceZohoDeskResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceZohoDeskResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceZohoDeskOutput(args: GetSourceZohoDeskOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceZohoDeskResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceZohoDesk:getSourceZohoDesk", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceZohoDesk.
 */
export interface GetSourceZohoDeskOutputArgs {
    sourceId: pulumi.Input<string>;
}
