// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceHoorayhr(args: GetSourceHoorayhrArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceHoorayhrResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceHoorayhr:getSourceHoorayhr", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceHoorayhr.
 */
export interface GetSourceHoorayhrArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceHoorayhr.
 */
export interface GetSourceHoorayhrResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceHoorayhrResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceHoorayhrOutput(args: GetSourceHoorayhrOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceHoorayhrResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceHoorayhr:getSourceHoorayhr", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceHoorayhr.
 */
export interface GetSourceHoorayhrOutputArgs {
    sourceId: pulumi.Input<string>;
}
