// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceDelighted(args: GetSourceDelightedArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceDelightedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceDelighted:getSourceDelighted", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceDelighted.
 */
export interface GetSourceDelightedArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceDelighted.
 */
export interface GetSourceDelightedResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceDelightedResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceDelightedOutput(args: GetSourceDelightedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceDelightedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceDelighted:getSourceDelighted", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceDelighted.
 */
export interface GetSourceDelightedOutputArgs {
    sourceId: pulumi.Input<string>;
}
