// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceTinyemail(args: GetSourceTinyemailArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceTinyemailResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceTinyemail:getSourceTinyemail", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceTinyemail.
 */
export interface GetSourceTinyemailArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceTinyemail.
 */
export interface GetSourceTinyemailResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceTinyemailResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceTinyemailOutput(args: GetSourceTinyemailOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceTinyemailResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceTinyemail:getSourceTinyemail", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceTinyemail.
 */
export interface GetSourceTinyemailOutputArgs {
    sourceId: pulumi.Input<string>;
}
