// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceSolarwindsServiceDesk(args: GetSourceSolarwindsServiceDeskArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSolarwindsServiceDeskResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSolarwindsServiceDesk:getSourceSolarwindsServiceDesk", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSolarwindsServiceDesk.
 */
export interface GetSourceSolarwindsServiceDeskArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSolarwindsServiceDesk.
 */
export interface GetSourceSolarwindsServiceDeskResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceSolarwindsServiceDeskResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceSolarwindsServiceDeskOutput(args: GetSourceSolarwindsServiceDeskOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceSolarwindsServiceDeskResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceSolarwindsServiceDesk:getSourceSolarwindsServiceDesk", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSolarwindsServiceDesk.
 */
export interface GetSourceSolarwindsServiceDeskOutputArgs {
    sourceId: pulumi.Input<string>;
}
