// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceBingAds(args: GetSourceBingAdsArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceBingAdsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceBingAds:getSourceBingAds", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBingAds.
 */
export interface GetSourceBingAdsArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceBingAds.
 */
export interface GetSourceBingAdsResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceBingAdsResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceBingAdsOutput(args: GetSourceBingAdsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceBingAdsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceBingAds:getSourceBingAds", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBingAds.
 */
export interface GetSourceBingAdsOutputArgs {
    sourceId: pulumi.Input<string>;
}
