// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceWasabiStatsApi(args: GetSourceWasabiStatsApiArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceWasabiStatsApiResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceWasabiStatsApi:getSourceWasabiStatsApi", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceWasabiStatsApi.
 */
export interface GetSourceWasabiStatsApiArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceWasabiStatsApi.
 */
export interface GetSourceWasabiStatsApiResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceWasabiStatsApiResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceWasabiStatsApiOutput(args: GetSourceWasabiStatsApiOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceWasabiStatsApiResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceWasabiStatsApi:getSourceWasabiStatsApi", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceWasabiStatsApi.
 */
export interface GetSourceWasabiStatsApiOutputArgs {
    sourceId: pulumi.Input<string>;
}
