// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceNylas(args: GetSourceNylasArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceNylasResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceNylas:getSourceNylas", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceNylas.
 */
export interface GetSourceNylasArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceNylas.
 */
export interface GetSourceNylasResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceNylasResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceNylasOutput(args: GetSourceNylasOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceNylasResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceNylas:getSourceNylas", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceNylas.
 */
export interface GetSourceNylasOutputArgs {
    sourceId: pulumi.Input<string>;
}
