// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceInflowinventory(args: GetSourceInflowinventoryArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceInflowinventoryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceInflowinventory:getSourceInflowinventory", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceInflowinventory.
 */
export interface GetSourceInflowinventoryArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceInflowinventory.
 */
export interface GetSourceInflowinventoryResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceInflowinventoryResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceInflowinventoryOutput(args: GetSourceInflowinventoryOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceInflowinventoryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceInflowinventory:getSourceInflowinventory", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceInflowinventory.
 */
export interface GetSourceInflowinventoryOutputArgs {
    sourceId: pulumi.Input<string>;
}
