// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceExchangeRates(args: GetSourceExchangeRatesArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceExchangeRatesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceExchangeRates:getSourceExchangeRates", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceExchangeRates.
 */
export interface GetSourceExchangeRatesArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceExchangeRates.
 */
export interface GetSourceExchangeRatesResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceExchangeRatesResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceExchangeRatesOutput(args: GetSourceExchangeRatesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceExchangeRatesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceExchangeRates:getSourceExchangeRates", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceExchangeRates.
 */
export interface GetSourceExchangeRatesOutputArgs {
    sourceId: pulumi.Input<string>;
}
