// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceBunnyInc(args: GetSourceBunnyIncArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceBunnyIncResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceBunnyInc:getSourceBunnyInc", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBunnyInc.
 */
export interface GetSourceBunnyIncArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceBunnyInc.
 */
export interface GetSourceBunnyIncResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceBunnyIncResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceBunnyIncOutput(args: GetSourceBunnyIncOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceBunnyIncResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceBunnyInc:getSourceBunnyInc", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBunnyInc.
 */
export interface GetSourceBunnyIncOutputArgs {
    sourceId: pulumi.Input<string>;
}
