// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceGiphy(args: GetSourceGiphyArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceGiphyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceGiphy:getSourceGiphy", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGiphy.
 */
export interface GetSourceGiphyArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceGiphy.
 */
export interface GetSourceGiphyResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceGiphyResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceGiphyOutput(args: GetSourceGiphyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceGiphyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceGiphy:getSourceGiphy", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGiphy.
 */
export interface GetSourceGiphyOutputArgs {
    sourceId: pulumi.Input<string>;
}
