// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceMarketstack(args: GetSourceMarketstackArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceMarketstackResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceMarketstack:getSourceMarketstack", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceMarketstack.
 */
export interface GetSourceMarketstackArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceMarketstack.
 */
export interface GetSourceMarketstackResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceMarketstackResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceMarketstackOutput(args: GetSourceMarketstackOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceMarketstackResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceMarketstack:getSourceMarketstack", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceMarketstack.
 */
export interface GetSourceMarketstackOutputArgs {
    sourceId: pulumi.Input<string>;
}
