// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceUppromote(args: GetSourceUppromoteArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceUppromoteResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceUppromote:getSourceUppromote", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceUppromote.
 */
export interface GetSourceUppromoteArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceUppromote.
 */
export interface GetSourceUppromoteResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceUppromoteResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceUppromoteOutput(args: GetSourceUppromoteOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceUppromoteResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceUppromote:getSourceUppromote", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceUppromote.
 */
export interface GetSourceUppromoteOutputArgs {
    sourceId: pulumi.Input<string>;
}
