// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceGoogleWebfonts(args: GetSourceGoogleWebfontsArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceGoogleWebfontsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceGoogleWebfonts:getSourceGoogleWebfonts", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGoogleWebfonts.
 */
export interface GetSourceGoogleWebfontsArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceGoogleWebfonts.
 */
export interface GetSourceGoogleWebfontsResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceGoogleWebfontsResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceGoogleWebfontsOutput(args: GetSourceGoogleWebfontsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceGoogleWebfontsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceGoogleWebfonts:getSourceGoogleWebfonts", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGoogleWebfonts.
 */
export interface GetSourceGoogleWebfontsOutputArgs {
    sourceId: pulumi.Input<string>;
}
