// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceWorkflowmax(args: GetSourceWorkflowmaxArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceWorkflowmaxResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceWorkflowmax:getSourceWorkflowmax", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceWorkflowmax.
 */
export interface GetSourceWorkflowmaxArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceWorkflowmax.
 */
export interface GetSourceWorkflowmaxResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceWorkflowmaxResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceWorkflowmaxOutput(args: GetSourceWorkflowmaxOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceWorkflowmaxResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceWorkflowmax:getSourceWorkflowmax", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceWorkflowmax.
 */
export interface GetSourceWorkflowmaxOutputArgs {
    sourceId: pulumi.Input<string>;
}
