// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSourceBrevo(args: GetSourceBrevoArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceBrevoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceBrevo:getSourceBrevo", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBrevo.
 */
export interface GetSourceBrevoArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceBrevo.
 */
export interface GetSourceBrevoResult {
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceBrevoOutput(args: GetSourceBrevoOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceBrevoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceBrevo:getSourceBrevo", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBrevo.
 */
export interface GetSourceBrevoOutputArgs {
    sourceId: pulumi.Input<string>;
}
