// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceDrift(args: GetSourceDriftArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceDriftResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceDrift:getSourceDrift", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceDrift.
 */
export interface GetSourceDriftArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceDrift.
 */
export interface GetSourceDriftResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceDriftResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceDriftOutput(args: GetSourceDriftOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceDriftResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceDrift:getSourceDrift", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceDrift.
 */
export interface GetSourceDriftOutputArgs {
    sourceId: pulumi.Input<string>;
}
