// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceClarifAi(args: GetSourceClarifAiArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceClarifAiResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceClarifAi:getSourceClarifAi", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceClarifAi.
 */
export interface GetSourceClarifAiArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceClarifAi.
 */
export interface GetSourceClarifAiResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceClarifAiResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceClarifAiOutput(args: GetSourceClarifAiOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceClarifAiResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceClarifAi:getSourceClarifAi", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceClarifAi.
 */
export interface GetSourceClarifAiOutputArgs {
    sourceId: pulumi.Input<string>;
}
