// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceSparkpost(args: GetSourceSparkpostArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSparkpostResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSparkpost:getSourceSparkpost", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSparkpost.
 */
export interface GetSourceSparkpostArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSparkpost.
 */
export interface GetSourceSparkpostResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceSparkpostResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceSparkpostOutput(args: GetSourceSparkpostOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceSparkpostResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceSparkpost:getSourceSparkpost", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSparkpost.
 */
export interface GetSourceSparkpostOutputArgs {
    sourceId: pulumi.Input<string>;
}
