// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSourceLeadfeeder(args: GetSourceLeadfeederArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceLeadfeederResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceLeadfeeder:getSourceLeadfeeder", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceLeadfeeder.
 */
export interface GetSourceLeadfeederArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceLeadfeeder.
 */
export interface GetSourceLeadfeederResult {
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceLeadfeederOutput(args: GetSourceLeadfeederOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceLeadfeederResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceLeadfeeder:getSourceLeadfeeder", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceLeadfeeder.
 */
export interface GetSourceLeadfeederOutputArgs {
    sourceId: pulumi.Input<string>;
}
