// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceGooglePagespeedInsights(args: GetSourceGooglePagespeedInsightsArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceGooglePagespeedInsightsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceGooglePagespeedInsights:getSourceGooglePagespeedInsights", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGooglePagespeedInsights.
 */
export interface GetSourceGooglePagespeedInsightsArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceGooglePagespeedInsights.
 */
export interface GetSourceGooglePagespeedInsightsResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceGooglePagespeedInsightsResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceGooglePagespeedInsightsOutput(args: GetSourceGooglePagespeedInsightsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceGooglePagespeedInsightsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceGooglePagespeedInsights:getSourceGooglePagespeedInsights", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGooglePagespeedInsights.
 */
export interface GetSourceGooglePagespeedInsightsOutputArgs {
    sourceId: pulumi.Input<string>;
}
