// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceIntercom(args: GetSourceIntercomArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceIntercomResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceIntercom:getSourceIntercom", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceIntercom.
 */
export interface GetSourceIntercomArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceIntercom.
 */
export interface GetSourceIntercomResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceIntercomResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceIntercomOutput(args: GetSourceIntercomOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceIntercomResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceIntercom:getSourceIntercom", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceIntercom.
 */
export interface GetSourceIntercomOutputArgs {
    sourceId: pulumi.Input<string>;
}
