// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceTestrail(args: GetSourceTestrailArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceTestrailResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceTestrail:getSourceTestrail", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceTestrail.
 */
export interface GetSourceTestrailArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceTestrail.
 */
export interface GetSourceTestrailResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceTestrailResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceTestrailOutput(args: GetSourceTestrailOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceTestrailResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceTestrail:getSourceTestrail", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceTestrail.
 */
export interface GetSourceTestrailOutputArgs {
    sourceId: pulumi.Input<string>;
}
