// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceSpotlercrm(args: GetSourceSpotlercrmArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSpotlercrmResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSpotlercrm:getSourceSpotlercrm", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSpotlercrm.
 */
export interface GetSourceSpotlercrmArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSpotlercrm.
 */
export interface GetSourceSpotlercrmResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceSpotlercrmResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceSpotlercrmOutput(args: GetSourceSpotlercrmOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceSpotlercrmResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceSpotlercrm:getSourceSpotlercrm", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSpotlercrm.
 */
export interface GetSourceSpotlercrmOutputArgs {
    sourceId: pulumi.Input<string>;
}
