// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceReplyIo(args: GetSourceReplyIoArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceReplyIoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceReplyIo:getSourceReplyIo", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceReplyIo.
 */
export interface GetSourceReplyIoArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceReplyIo.
 */
export interface GetSourceReplyIoResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceReplyIoResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceReplyIoOutput(args: GetSourceReplyIoOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceReplyIoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceReplyIo:getSourceReplyIo", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceReplyIo.
 */
export interface GetSourceReplyIoOutputArgs {
    sourceId: pulumi.Input<string>;
}
