// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceDwolla(args: GetSourceDwollaArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceDwollaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceDwolla:getSourceDwolla", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceDwolla.
 */
export interface GetSourceDwollaArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceDwolla.
 */
export interface GetSourceDwollaResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceDwollaResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceDwollaOutput(args: GetSourceDwollaOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceDwollaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceDwolla:getSourceDwolla", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceDwolla.
 */
export interface GetSourceDwollaOutputArgs {
    sourceId: pulumi.Input<string>;
}
