// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceSimplesat(args: GetSourceSimplesatArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSimplesatResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSimplesat:getSourceSimplesat", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSimplesat.
 */
export interface GetSourceSimplesatArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSimplesat.
 */
export interface GetSourceSimplesatResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceSimplesatResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceSimplesatOutput(args: GetSourceSimplesatOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceSimplesatResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceSimplesat:getSourceSimplesat", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSimplesat.
 */
export interface GetSourceSimplesatOutputArgs {
    sourceId: pulumi.Input<string>;
}
