// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceGorgias(args: GetSourceGorgiasArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceGorgiasResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceGorgias:getSourceGorgias", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGorgias.
 */
export interface GetSourceGorgiasArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceGorgias.
 */
export interface GetSourceGorgiasResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceGorgiasResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceGorgiasOutput(args: GetSourceGorgiasOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceGorgiasResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceGorgias:getSourceGorgias", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGorgias.
 */
export interface GetSourceGorgiasOutputArgs {
    sourceId: pulumi.Input<string>;
}
