// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceCustomerly(args: GetSourceCustomerlyArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceCustomerlyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceCustomerly:getSourceCustomerly", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCustomerly.
 */
export interface GetSourceCustomerlyArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceCustomerly.
 */
export interface GetSourceCustomerlyResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceCustomerlyResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceCustomerlyOutput(args: GetSourceCustomerlyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceCustomerlyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceCustomerly:getSourceCustomerly", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCustomerly.
 */
export interface GetSourceCustomerlyOutputArgs {
    sourceId: pulumi.Input<string>;
}
