// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourcePennylane(args: GetSourcePennylaneArgs, opts?: pulumi.InvokeOptions): Promise<GetSourcePennylaneResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourcePennylane:getSourcePennylane", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePennylane.
 */
export interface GetSourcePennylaneArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourcePennylane.
 */
export interface GetSourcePennylaneResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourcePennylaneResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourcePennylaneOutput(args: GetSourcePennylaneOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourcePennylaneResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourcePennylane:getSourcePennylane", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePennylane.
 */
export interface GetSourcePennylaneOutputArgs {
    sourceId: pulumi.Input<string>;
}
