// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceEasypost(args: GetSourceEasypostArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceEasypostResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceEasypost:getSourceEasypost", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceEasypost.
 */
export interface GetSourceEasypostArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceEasypost.
 */
export interface GetSourceEasypostResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceEasypostResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceEasypostOutput(args: GetSourceEasypostOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceEasypostResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceEasypost:getSourceEasypost", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceEasypost.
 */
export interface GetSourceEasypostOutputArgs {
    sourceId: pulumi.Input<string>;
}
