// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceWrike(args: GetSourceWrikeArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceWrikeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceWrike:getSourceWrike", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceWrike.
 */
export interface GetSourceWrikeArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceWrike.
 */
export interface GetSourceWrikeResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceWrikeResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceWrikeOutput(args: GetSourceWrikeOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceWrikeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceWrike:getSourceWrike", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceWrike.
 */
export interface GetSourceWrikeOutputArgs {
    sourceId: pulumi.Input<string>;
}
