// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceBeamer(args: GetSourceBeamerArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceBeamerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceBeamer:getSourceBeamer", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBeamer.
 */
export interface GetSourceBeamerArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceBeamer.
 */
export interface GetSourceBeamerResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceBeamerResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceBeamerOutput(args: GetSourceBeamerOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceBeamerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceBeamer:getSourceBeamer", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBeamer.
 */
export interface GetSourceBeamerOutputArgs {
    sourceId: pulumi.Input<string>;
}
