// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceNasa(args: GetSourceNasaArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceNasaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceNasa:getSourceNasa", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceNasa.
 */
export interface GetSourceNasaArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceNasa.
 */
export interface GetSourceNasaResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceNasaResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceNasaOutput(args: GetSourceNasaOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceNasaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceNasa:getSourceNasa", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceNasa.
 */
export interface GetSourceNasaOutputArgs {
    sourceId: pulumi.Input<string>;
}
