// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceXkcd(args: GetSourceXkcdArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceXkcdResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceXkcd:getSourceXkcd", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceXkcd.
 */
export interface GetSourceXkcdArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceXkcd.
 */
export interface GetSourceXkcdResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceXkcdResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceXkcdOutput(args: GetSourceXkcdOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceXkcdResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceXkcd:getSourceXkcd", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceXkcd.
 */
export interface GetSourceXkcdOutputArgs {
    sourceId: pulumi.Input<string>;
}
