// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceUnleash(args: GetSourceUnleashArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceUnleashResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceUnleash:getSourceUnleash", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceUnleash.
 */
export interface GetSourceUnleashArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceUnleash.
 */
export interface GetSourceUnleashResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceUnleashResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceUnleashOutput(args: GetSourceUnleashOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceUnleashResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceUnleash:getSourceUnleash", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceUnleash.
 */
export interface GetSourceUnleashOutputArgs {
    sourceId: pulumi.Input<string>;
}
