// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceConcord(args: GetSourceConcordArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceConcordResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceConcord:getSourceConcord", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceConcord.
 */
export interface GetSourceConcordArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceConcord.
 */
export interface GetSourceConcordResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceConcordResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceConcordOutput(args: GetSourceConcordOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceConcordResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceConcord:getSourceConcord", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceConcord.
 */
export interface GetSourceConcordOutputArgs {
    sourceId: pulumi.Input<string>;
}
