// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSourceBitly(args: GetSourceBitlyArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceBitlyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceBitly:getSourceBitly", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBitly.
 */
export interface GetSourceBitlyArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceBitly.
 */
export interface GetSourceBitlyResult {
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceBitlyOutput(args: GetSourceBitlyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceBitlyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceBitly:getSourceBitly", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBitly.
 */
export interface GetSourceBitlyOutputArgs {
    sourceId: pulumi.Input<string>;
}
