// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceCimis(args: GetSourceCimisArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceCimisResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceCimis:getSourceCimis", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCimis.
 */
export interface GetSourceCimisArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceCimis.
 */
export interface GetSourceCimisResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceCimisResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceCimisOutput(args: GetSourceCimisOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceCimisResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceCimis:getSourceCimis", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCimis.
 */
export interface GetSourceCimisOutputArgs {
    sourceId: pulumi.Input<string>;
}
