// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceTmdb(args: GetSourceTmdbArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceTmdbResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceTmdb:getSourceTmdb", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceTmdb.
 */
export interface GetSourceTmdbArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceTmdb.
 */
export interface GetSourceTmdbResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceTmdbResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceTmdbOutput(args: GetSourceTmdbOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceTmdbResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceTmdb:getSourceTmdb", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceTmdb.
 */
export interface GetSourceTmdbOutputArgs {
    sourceId: pulumi.Input<string>;
}
