// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSourceSavvycal(args: GetSourceSavvycalArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSavvycalResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSavvycal:getSourceSavvycal", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSavvycal.
 */
export interface GetSourceSavvycalArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSavvycal.
 */
export interface GetSourceSavvycalResult {
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceSavvycalOutput(args: GetSourceSavvycalOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceSavvycalResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceSavvycal:getSourceSavvycal", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSavvycal.
 */
export interface GetSourceSavvycalOutputArgs {
    sourceId: pulumi.Input<string>;
}
