// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceMicrosoftLists(args: GetSourceMicrosoftListsArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceMicrosoftListsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceMicrosoftLists:getSourceMicrosoftLists", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceMicrosoftLists.
 */
export interface GetSourceMicrosoftListsArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceMicrosoftLists.
 */
export interface GetSourceMicrosoftListsResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceMicrosoftListsResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceMicrosoftListsOutput(args: GetSourceMicrosoftListsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceMicrosoftListsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceMicrosoftLists:getSourceMicrosoftLists", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceMicrosoftLists.
 */
export interface GetSourceMicrosoftListsOutputArgs {
    sourceId: pulumi.Input<string>;
}
