// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceNewsApi(args: GetSourceNewsApiArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceNewsApiResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceNewsApi:getSourceNewsApi", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceNewsApi.
 */
export interface GetSourceNewsApiArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceNewsApi.
 */
export interface GetSourceNewsApiResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceNewsApiResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceNewsApiOutput(args: GetSourceNewsApiOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceNewsApiResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceNewsApi:getSourceNewsApi", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceNewsApi.
 */
export interface GetSourceNewsApiOutputArgs {
    sourceId: pulumi.Input<string>;
}
