// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceGoogleClassroom(args: GetSourceGoogleClassroomArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceGoogleClassroomResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceGoogleClassroom:getSourceGoogleClassroom", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGoogleClassroom.
 */
export interface GetSourceGoogleClassroomArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceGoogleClassroom.
 */
export interface GetSourceGoogleClassroomResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceGoogleClassroomResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceGoogleClassroomOutput(args: GetSourceGoogleClassroomOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceGoogleClassroomResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceGoogleClassroom:getSourceGoogleClassroom", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGoogleClassroom.
 */
export interface GetSourceGoogleClassroomOutputArgs {
    sourceId: pulumi.Input<string>;
}
