// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceMongodbV2(args: GetSourceMongodbV2Args, opts?: pulumi.InvokeOptions): Promise<GetSourceMongodbV2Result> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceMongodbV2:getSourceMongodbV2", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceMongodbV2.
 */
export interface GetSourceMongodbV2Args {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceMongodbV2.
 */
export interface GetSourceMongodbV2Result {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceMongodbV2ResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceMongodbV2Output(args: GetSourceMongodbV2OutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceMongodbV2Result> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceMongodbV2:getSourceMongodbV2", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceMongodbV2.
 */
export interface GetSourceMongodbV2OutputArgs {
    sourceId: pulumi.Input<string>;
}
