// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceSendpulse(args: GetSourceSendpulseArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSendpulseResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSendpulse:getSourceSendpulse", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSendpulse.
 */
export interface GetSourceSendpulseArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSendpulse.
 */
export interface GetSourceSendpulseResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceSendpulseResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceSendpulseOutput(args: GetSourceSendpulseOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceSendpulseResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceSendpulse:getSourceSendpulse", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSendpulse.
 */
export interface GetSourceSendpulseOutputArgs {
    sourceId: pulumi.Input<string>;
}
