// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceSquarespace(args: GetSourceSquarespaceArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSquarespaceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSquarespace:getSourceSquarespace", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSquarespace.
 */
export interface GetSourceSquarespaceArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSquarespace.
 */
export interface GetSourceSquarespaceResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceSquarespaceResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceSquarespaceOutput(args: GetSourceSquarespaceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceSquarespaceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceSquarespace:getSourceSquarespace", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSquarespace.
 */
export interface GetSourceSquarespaceOutputArgs {
    sourceId: pulumi.Input<string>;
}
