// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceInstagram(args: GetSourceInstagramArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceInstagramResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceInstagram:getSourceInstagram", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceInstagram.
 */
export interface GetSourceInstagramArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceInstagram.
 */
export interface GetSourceInstagramResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceInstagramResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceInstagramOutput(args: GetSourceInstagramOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceInstagramResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceInstagram:getSourceInstagram", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceInstagram.
 */
export interface GetSourceInstagramOutputArgs {
    sourceId: pulumi.Input<string>;
}
