// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceFulcrum(args: GetSourceFulcrumArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceFulcrumResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceFulcrum:getSourceFulcrum", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceFulcrum.
 */
export interface GetSourceFulcrumArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceFulcrum.
 */
export interface GetSourceFulcrumResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceFulcrumResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceFulcrumOutput(args: GetSourceFulcrumOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceFulcrumResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceFulcrum:getSourceFulcrum", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceFulcrum.
 */
export interface GetSourceFulcrumOutputArgs {
    sourceId: pulumi.Input<string>;
}
