// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceLinear(args: GetSourceLinearArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceLinearResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceLinear:getSourceLinear", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceLinear.
 */
export interface GetSourceLinearArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceLinear.
 */
export interface GetSourceLinearResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceLinearResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceLinearOutput(args: GetSourceLinearOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceLinearResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceLinear:getSourceLinear", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceLinear.
 */
export interface GetSourceLinearOutputArgs {
    sourceId: pulumi.Input<string>;
}
