// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceShortcut(args: GetSourceShortcutArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceShortcutResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceShortcut:getSourceShortcut", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceShortcut.
 */
export interface GetSourceShortcutArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceShortcut.
 */
export interface GetSourceShortcutResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceShortcutResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceShortcutOutput(args: GetSourceShortcutOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceShortcutResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceShortcut:getSourceShortcut", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceShortcut.
 */
export interface GetSourceShortcutOutputArgs {
    sourceId: pulumi.Input<string>;
}
