// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSourceDefinition(args: GetSourceDefinitionArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceDefinitionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceDefinition:getSourceDefinition", {
        "workspaceId": args.workspaceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceDefinition.
 */
export interface GetSourceDefinitionArgs {
    workspaceId: string;
}

/**
 * A collection of values returned by getSourceDefinition.
 */
export interface GetSourceDefinitionResult {
    readonly dockerImageTag: string;
    readonly dockerRepository: string;
    readonly documentationUrl: string;
    readonly id: string;
    readonly name: string;
    readonly workspaceId: string;
}
export function getSourceDefinitionOutput(args: GetSourceDefinitionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceDefinitionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceDefinition:getSourceDefinition", {
        "workspaceId": args.workspaceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceDefinition.
 */
export interface GetSourceDefinitionOutputArgs {
    workspaceId: pulumi.Input<string>;
}
