// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceAssemblyai(args: GetSourceAssemblyaiArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceAssemblyaiResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceAssemblyai:getSourceAssemblyai", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceAssemblyai.
 */
export interface GetSourceAssemblyaiArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceAssemblyai.
 */
export interface GetSourceAssemblyaiResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceAssemblyaiResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceAssemblyaiOutput(args: GetSourceAssemblyaiOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceAssemblyaiResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceAssemblyai:getSourceAssemblyai", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceAssemblyai.
 */
export interface GetSourceAssemblyaiOutputArgs {
    sourceId: pulumi.Input<string>;
}
