// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceNinjaoneRmm(args: GetSourceNinjaoneRmmArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceNinjaoneRmmResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceNinjaoneRmm:getSourceNinjaoneRmm", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceNinjaoneRmm.
 */
export interface GetSourceNinjaoneRmmArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceNinjaoneRmm.
 */
export interface GetSourceNinjaoneRmmResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceNinjaoneRmmResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceNinjaoneRmmOutput(args: GetSourceNinjaoneRmmOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceNinjaoneRmmResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceNinjaoneRmm:getSourceNinjaoneRmm", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceNinjaoneRmm.
 */
export interface GetSourceNinjaoneRmmOutputArgs {
    sourceId: pulumi.Input<string>;
}
