// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceCastorEdc(args: GetSourceCastorEdcArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceCastorEdcResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceCastorEdc:getSourceCastorEdc", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCastorEdc.
 */
export interface GetSourceCastorEdcArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceCastorEdc.
 */
export interface GetSourceCastorEdcResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceCastorEdcResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceCastorEdcOutput(args: GetSourceCastorEdcOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceCastorEdcResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceCastorEdc:getSourceCastorEdc", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCastorEdc.
 */
export interface GetSourceCastorEdcOutputArgs {
    sourceId: pulumi.Input<string>;
}
