// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceTvmazeSchedule(args: GetSourceTvmazeScheduleArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceTvmazeScheduleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceTvmazeSchedule:getSourceTvmazeSchedule", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceTvmazeSchedule.
 */
export interface GetSourceTvmazeScheduleArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceTvmazeSchedule.
 */
export interface GetSourceTvmazeScheduleResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceTvmazeScheduleResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceTvmazeScheduleOutput(args: GetSourceTvmazeScheduleOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceTvmazeScheduleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceTvmazeSchedule:getSourceTvmazeSchedule", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceTvmazeSchedule.
 */
export interface GetSourceTvmazeScheduleOutputArgs {
    sourceId: pulumi.Input<string>;
}
