// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSourceDatadog(args: GetSourceDatadogArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceDatadogResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceDatadog:getSourceDatadog", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceDatadog.
 */
export interface GetSourceDatadogArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceDatadog.
 */
export interface GetSourceDatadogResult {
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceDatadogOutput(args: GetSourceDatadogOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceDatadogResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceDatadog:getSourceDatadog", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceDatadog.
 */
export interface GetSourceDatadogOutputArgs {
    sourceId: pulumi.Input<string>;
}
