// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceIlluminaBasespace(args: GetSourceIlluminaBasespaceArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceIlluminaBasespaceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceIlluminaBasespace:getSourceIlluminaBasespace", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceIlluminaBasespace.
 */
export interface GetSourceIlluminaBasespaceArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceIlluminaBasespace.
 */
export interface GetSourceIlluminaBasespaceResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceIlluminaBasespaceResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceIlluminaBasespaceOutput(args: GetSourceIlluminaBasespaceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceIlluminaBasespaceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceIlluminaBasespace:getSourceIlluminaBasespace", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceIlluminaBasespace.
 */
export interface GetSourceIlluminaBasespaceOutputArgs {
    sourceId: pulumi.Input<string>;
}
