// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceShopwired(args: GetSourceShopwiredArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceShopwiredResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceShopwired:getSourceShopwired", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceShopwired.
 */
export interface GetSourceShopwiredArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceShopwired.
 */
export interface GetSourceShopwiredResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceShopwiredResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceShopwiredOutput(args: GetSourceShopwiredOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceShopwiredResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceShopwired:getSourceShopwired", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceShopwired.
 */
export interface GetSourceShopwiredOutputArgs {
    sourceId: pulumi.Input<string>;
}
