// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceFastly(args: GetSourceFastlyArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceFastlyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceFastly:getSourceFastly", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceFastly.
 */
export interface GetSourceFastlyArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceFastly.
 */
export interface GetSourceFastlyResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceFastlyResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceFastlyOutput(args: GetSourceFastlyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceFastlyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceFastly:getSourceFastly", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceFastly.
 */
export interface GetSourceFastlyOutputArgs {
    sourceId: pulumi.Input<string>;
}
