// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceZohoBooks(args: GetSourceZohoBooksArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceZohoBooksResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceZohoBooks:getSourceZohoBooks", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceZohoBooks.
 */
export interface GetSourceZohoBooksArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceZohoBooks.
 */
export interface GetSourceZohoBooksResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceZohoBooksResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceZohoBooksOutput(args: GetSourceZohoBooksOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceZohoBooksResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceZohoBooks:getSourceZohoBooks", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceZohoBooks.
 */
export interface GetSourceZohoBooksOutputArgs {
    sourceId: pulumi.Input<string>;
}
