// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceSimfin(args: GetSourceSimfinArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSimfinResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSimfin:getSourceSimfin", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSimfin.
 */
export interface GetSourceSimfinArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSimfin.
 */
export interface GetSourceSimfinResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceSimfinResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceSimfinOutput(args: GetSourceSimfinOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceSimfinResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceSimfin:getSourceSimfin", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSimfin.
 */
export interface GetSourceSimfinOutputArgs {
    sourceId: pulumi.Input<string>;
}
