// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceInvoiced(args: GetSourceInvoicedArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceInvoicedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceInvoiced:getSourceInvoiced", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceInvoiced.
 */
export interface GetSourceInvoicedArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceInvoiced.
 */
export interface GetSourceInvoicedResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceInvoicedResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceInvoicedOutput(args: GetSourceInvoicedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceInvoicedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceInvoiced:getSourceInvoiced", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceInvoiced.
 */
export interface GetSourceInvoicedOutputArgs {
    sourceId: pulumi.Input<string>;
}
