// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceSignnow(args: GetSourceSignnowArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSignnowResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSignnow:getSourceSignnow", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSignnow.
 */
export interface GetSourceSignnowArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSignnow.
 */
export interface GetSourceSignnowResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceSignnowResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceSignnowOutput(args: GetSourceSignnowOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceSignnowResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceSignnow:getSourceSignnow", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSignnow.
 */
export interface GetSourceSignnowOutputArgs {
    sourceId: pulumi.Input<string>;
}
