// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceOpenaq(args: GetSourceOpenaqArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceOpenaqResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceOpenaq:getSourceOpenaq", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceOpenaq.
 */
export interface GetSourceOpenaqArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceOpenaq.
 */
export interface GetSourceOpenaqResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceOpenaqResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceOpenaqOutput(args: GetSourceOpenaqOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceOpenaqResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceOpenaq:getSourceOpenaq", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceOpenaq.
 */
export interface GetSourceOpenaqOutputArgs {
    sourceId: pulumi.Input<string>;
}
