// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceEmploymentHero(args: GetSourceEmploymentHeroArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceEmploymentHeroResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceEmploymentHero:getSourceEmploymentHero", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceEmploymentHero.
 */
export interface GetSourceEmploymentHeroArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceEmploymentHero.
 */
export interface GetSourceEmploymentHeroResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceEmploymentHeroResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceEmploymentHeroOutput(args: GetSourceEmploymentHeroOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceEmploymentHeroResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceEmploymentHero:getSourceEmploymentHero", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceEmploymentHero.
 */
export interface GetSourceEmploymentHeroOutputArgs {
    sourceId: pulumi.Input<string>;
}
