// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceStockdata(args: GetSourceStockdataArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceStockdataResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceStockdata:getSourceStockdata", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceStockdata.
 */
export interface GetSourceStockdataArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceStockdata.
 */
export interface GetSourceStockdataResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceStockdataResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceStockdataOutput(args: GetSourceStockdataOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceStockdataResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceStockdata:getSourceStockdata", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceStockdata.
 */
export interface GetSourceStockdataOutputArgs {
    sourceId: pulumi.Input<string>;
}
