// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceBluetally(args: GetSourceBluetallyArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceBluetallyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceBluetally:getSourceBluetally", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBluetally.
 */
export interface GetSourceBluetallyArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceBluetally.
 */
export interface GetSourceBluetallyResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceBluetallyResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceBluetallyOutput(args: GetSourceBluetallyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceBluetallyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceBluetally:getSourceBluetally", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBluetally.
 */
export interface GetSourceBluetallyOutputArgs {
    sourceId: pulumi.Input<string>;
}
