// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceSurvicate(args: GetSourceSurvicateArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSurvicateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSurvicate:getSourceSurvicate", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSurvicate.
 */
export interface GetSourceSurvicateArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSurvicate.
 */
export interface GetSourceSurvicateResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceSurvicateResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceSurvicateOutput(args: GetSourceSurvicateOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceSurvicateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceSurvicate:getSourceSurvicate", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSurvicate.
 */
export interface GetSourceSurvicateOutputArgs {
    sourceId: pulumi.Input<string>;
}
