// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceSerpstat(args: GetSourceSerpstatArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSerpstatResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSerpstat:getSourceSerpstat", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSerpstat.
 */
export interface GetSourceSerpstatArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSerpstat.
 */
export interface GetSourceSerpstatResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceSerpstatResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceSerpstatOutput(args: GetSourceSerpstatOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceSerpstatResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceSerpstat:getSourceSerpstat", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSerpstat.
 */
export interface GetSourceSerpstatOutputArgs {
    sourceId: pulumi.Input<string>;
}
