// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceFreshservice(args: GetSourceFreshserviceArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceFreshserviceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceFreshservice:getSourceFreshservice", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceFreshservice.
 */
export interface GetSourceFreshserviceArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceFreshservice.
 */
export interface GetSourceFreshserviceResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceFreshserviceResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceFreshserviceOutput(args: GetSourceFreshserviceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceFreshserviceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceFreshservice:getSourceFreshservice", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceFreshservice.
 */
export interface GetSourceFreshserviceOutputArgs {
    sourceId: pulumi.Input<string>;
}
