// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceBuzzsprout(args: GetSourceBuzzsproutArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceBuzzsproutResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceBuzzsprout:getSourceBuzzsprout", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBuzzsprout.
 */
export interface GetSourceBuzzsproutArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceBuzzsprout.
 */
export interface GetSourceBuzzsproutResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceBuzzsproutResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceBuzzsproutOutput(args: GetSourceBuzzsproutOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceBuzzsproutResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceBuzzsprout:getSourceBuzzsprout", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceBuzzsprout.
 */
export interface GetSourceBuzzsproutOutputArgs {
    sourceId: pulumi.Input<string>;
}
