// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceInsightful(args: GetSourceInsightfulArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceInsightfulResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceInsightful:getSourceInsightful", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceInsightful.
 */
export interface GetSourceInsightfulArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceInsightful.
 */
export interface GetSourceInsightfulResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceInsightfulResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceInsightfulOutput(args: GetSourceInsightfulOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceInsightfulResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceInsightful:getSourceInsightful", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceInsightful.
 */
export interface GetSourceInsightfulOutputArgs {
    sourceId: pulumi.Input<string>;
}
