// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceSmartsheets(args: GetSourceSmartsheetsArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSmartsheetsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSmartsheets:getSourceSmartsheets", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSmartsheets.
 */
export interface GetSourceSmartsheetsArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSmartsheets.
 */
export interface GetSourceSmartsheetsResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceSmartsheetsResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceSmartsheetsOutput(args: GetSourceSmartsheetsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceSmartsheetsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceSmartsheets:getSourceSmartsheets", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSmartsheets.
 */
export interface GetSourceSmartsheetsOutputArgs {
    sourceId: pulumi.Input<string>;
}
