// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceOnfleet(args: GetSourceOnfleetArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceOnfleetResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceOnfleet:getSourceOnfleet", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceOnfleet.
 */
export interface GetSourceOnfleetArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceOnfleet.
 */
export interface GetSourceOnfleetResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceOnfleetResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceOnfleetOutput(args: GetSourceOnfleetOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceOnfleetResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceOnfleet:getSourceOnfleet", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceOnfleet.
 */
export interface GetSourceOnfleetOutputArgs {
    sourceId: pulumi.Input<string>;
}
