// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceGitbook(args: GetSourceGitbookArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceGitbookResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceGitbook:getSourceGitbook", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGitbook.
 */
export interface GetSourceGitbookArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceGitbook.
 */
export interface GetSourceGitbookResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceGitbookResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceGitbookOutput(args: GetSourceGitbookOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceGitbookResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceGitbook:getSourceGitbook", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGitbook.
 */
export interface GetSourceGitbookOutputArgs {
    sourceId: pulumi.Input<string>;
}
