// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceVercel(args: GetSourceVercelArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceVercelResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceVercel:getSourceVercel", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceVercel.
 */
export interface GetSourceVercelArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceVercel.
 */
export interface GetSourceVercelResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceVercelResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceVercelOutput(args: GetSourceVercelOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceVercelResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceVercel:getSourceVercel", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceVercel.
 */
export interface GetSourceVercelOutputArgs {
    sourceId: pulumi.Input<string>;
}
