// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceCloudbeds(args: GetSourceCloudbedsArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceCloudbedsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceCloudbeds:getSourceCloudbeds", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCloudbeds.
 */
export interface GetSourceCloudbedsArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceCloudbeds.
 */
export interface GetSourceCloudbedsResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceCloudbedsResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceCloudbedsOutput(args: GetSourceCloudbedsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceCloudbedsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceCloudbeds:getSourceCloudbeds", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCloudbeds.
 */
export interface GetSourceCloudbedsOutputArgs {
    sourceId: pulumi.Input<string>;
}
