// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceVismaEconomic(args: GetSourceVismaEconomicArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceVismaEconomicResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceVismaEconomic:getSourceVismaEconomic", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceVismaEconomic.
 */
export interface GetSourceVismaEconomicArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceVismaEconomic.
 */
export interface GetSourceVismaEconomicResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceVismaEconomicResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceVismaEconomicOutput(args: GetSourceVismaEconomicOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceVismaEconomicResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceVismaEconomic:getSourceVismaEconomic", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceVismaEconomic.
 */
export interface GetSourceVismaEconomicOutputArgs {
    sourceId: pulumi.Input<string>;
}
