// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourcePayfit(args: GetSourcePayfitArgs, opts?: pulumi.InvokeOptions): Promise<GetSourcePayfitResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourcePayfit:getSourcePayfit", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePayfit.
 */
export interface GetSourcePayfitArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourcePayfit.
 */
export interface GetSourcePayfitResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourcePayfitResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourcePayfitOutput(args: GetSourcePayfitOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourcePayfitResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourcePayfit:getSourcePayfit", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePayfit.
 */
export interface GetSourcePayfitOutputArgs {
    sourceId: pulumi.Input<string>;
}
