// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSourceTeamwork(args: GetSourceTeamworkArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceTeamworkResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceTeamwork:getSourceTeamwork", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceTeamwork.
 */
export interface GetSourceTeamworkArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceTeamwork.
 */
export interface GetSourceTeamworkResult {
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceTeamworkOutput(args: GetSourceTeamworkOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceTeamworkResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceTeamwork:getSourceTeamwork", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceTeamwork.
 */
export interface GetSourceTeamworkOutputArgs {
    sourceId: pulumi.Input<string>;
}
