// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceGutendex(args: GetSourceGutendexArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceGutendexResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceGutendex:getSourceGutendex", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGutendex.
 */
export interface GetSourceGutendexArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceGutendex.
 */
export interface GetSourceGutendexResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceGutendexResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceGutendexOutput(args: GetSourceGutendexOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceGutendexResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceGutendex:getSourceGutendex", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGutendex.
 */
export interface GetSourceGutendexOutputArgs {
    sourceId: pulumi.Input<string>;
}
