// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceTeamtailor(args: GetSourceTeamtailorArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceTeamtailorResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceTeamtailor:getSourceTeamtailor", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceTeamtailor.
 */
export interface GetSourceTeamtailorArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceTeamtailor.
 */
export interface GetSourceTeamtailorResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceTeamtailorResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceTeamtailorOutput(args: GetSourceTeamtailorOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceTeamtailorResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceTeamtailor:getSourceTeamtailor", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceTeamtailor.
 */
export interface GetSourceTeamtailorOutputArgs {
    sourceId: pulumi.Input<string>;
}
