// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceCiscoMeraki(args: GetSourceCiscoMerakiArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceCiscoMerakiResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceCiscoMeraki:getSourceCiscoMeraki", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCiscoMeraki.
 */
export interface GetSourceCiscoMerakiArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceCiscoMeraki.
 */
export interface GetSourceCiscoMerakiResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceCiscoMerakiResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceCiscoMerakiOutput(args: GetSourceCiscoMerakiOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceCiscoMerakiResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceCiscoMeraki:getSourceCiscoMeraki", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCiscoMeraki.
 */
export interface GetSourceCiscoMerakiOutputArgs {
    sourceId: pulumi.Input<string>;
}
