// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceRepairshopr(args: GetSourceRepairshoprArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceRepairshoprResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceRepairshopr:getSourceRepairshopr", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceRepairshopr.
 */
export interface GetSourceRepairshoprArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceRepairshopr.
 */
export interface GetSourceRepairshoprResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceRepairshoprResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceRepairshoprOutput(args: GetSourceRepairshoprOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceRepairshoprResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceRepairshopr:getSourceRepairshopr", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceRepairshopr.
 */
export interface GetSourceRepairshoprOutputArgs {
    sourceId: pulumi.Input<string>;
}
