// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceGologin(args: GetSourceGologinArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceGologinResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceGologin:getSourceGologin", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGologin.
 */
export interface GetSourceGologinArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceGologin.
 */
export interface GetSourceGologinResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceGologinResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceGologinOutput(args: GetSourceGologinOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceGologinResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceGologin:getSourceGologin", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGologin.
 */
export interface GetSourceGologinOutputArgs {
    sourceId: pulumi.Input<string>;
}
