// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourcePivotalTracker(args: GetSourcePivotalTrackerArgs, opts?: pulumi.InvokeOptions): Promise<GetSourcePivotalTrackerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourcePivotalTracker:getSourcePivotalTracker", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePivotalTracker.
 */
export interface GetSourcePivotalTrackerArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourcePivotalTracker.
 */
export interface GetSourcePivotalTrackerResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourcePivotalTrackerResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourcePivotalTrackerOutput(args: GetSourcePivotalTrackerOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourcePivotalTrackerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourcePivotalTracker:getSourcePivotalTracker", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePivotalTracker.
 */
export interface GetSourcePivotalTrackerOutputArgs {
    sourceId: pulumi.Input<string>;
}
