// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceAwsCloudtrail(args: GetSourceAwsCloudtrailArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceAwsCloudtrailResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceAwsCloudtrail:getSourceAwsCloudtrail", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceAwsCloudtrail.
 */
export interface GetSourceAwsCloudtrailArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceAwsCloudtrail.
 */
export interface GetSourceAwsCloudtrailResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceAwsCloudtrailResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceAwsCloudtrailOutput(args: GetSourceAwsCloudtrailOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceAwsCloudtrailResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceAwsCloudtrail:getSourceAwsCloudtrail", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceAwsCloudtrail.
 */
export interface GetSourceAwsCloudtrailOutputArgs {
    sourceId: pulumi.Input<string>;
}
