// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourcePrintify(args: GetSourcePrintifyArgs, opts?: pulumi.InvokeOptions): Promise<GetSourcePrintifyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourcePrintify:getSourcePrintify", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePrintify.
 */
export interface GetSourcePrintifyArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourcePrintify.
 */
export interface GetSourcePrintifyResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourcePrintifyResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourcePrintifyOutput(args: GetSourcePrintifyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourcePrintifyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourcePrintify:getSourcePrintify", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePrintify.
 */
export interface GetSourcePrintifyOutputArgs {
    sourceId: pulumi.Input<string>;
}
