// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceWaiteraid(args: GetSourceWaiteraidArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceWaiteraidResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceWaiteraid:getSourceWaiteraid", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceWaiteraid.
 */
export interface GetSourceWaiteraidArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceWaiteraid.
 */
export interface GetSourceWaiteraidResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceWaiteraidResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceWaiteraidOutput(args: GetSourceWaiteraidOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceWaiteraidResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceWaiteraid:getSourceWaiteraid", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceWaiteraid.
 */
export interface GetSourceWaiteraidOutputArgs {
    sourceId: pulumi.Input<string>;
}
