// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourcePaperform(args: GetSourcePaperformArgs, opts?: pulumi.InvokeOptions): Promise<GetSourcePaperformResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourcePaperform:getSourcePaperform", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePaperform.
 */
export interface GetSourcePaperformArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourcePaperform.
 */
export interface GetSourcePaperformResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourcePaperformResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourcePaperformOutput(args: GetSourcePaperformOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourcePaperformResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourcePaperform:getSourcePaperform", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePaperform.
 */
export interface GetSourcePaperformOutputArgs {
    sourceId: pulumi.Input<string>;
}
