// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceCoingeckoCoins(args: GetSourceCoingeckoCoinsArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceCoingeckoCoinsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceCoingeckoCoins:getSourceCoingeckoCoins", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCoingeckoCoins.
 */
export interface GetSourceCoingeckoCoinsArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceCoingeckoCoins.
 */
export interface GetSourceCoingeckoCoinsResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceCoingeckoCoinsResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceCoingeckoCoinsOutput(args: GetSourceCoingeckoCoinsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceCoingeckoCoinsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceCoingeckoCoins:getSourceCoingeckoCoins", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCoingeckoCoins.
 */
export interface GetSourceCoingeckoCoinsOutputArgs {
    sourceId: pulumi.Input<string>;
}
