// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourcePartnerstack(args: GetSourcePartnerstackArgs, opts?: pulumi.InvokeOptions): Promise<GetSourcePartnerstackResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourcePartnerstack:getSourcePartnerstack", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePartnerstack.
 */
export interface GetSourcePartnerstackArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourcePartnerstack.
 */
export interface GetSourcePartnerstackResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourcePartnerstackResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourcePartnerstackOutput(args: GetSourcePartnerstackOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourcePartnerstackResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourcePartnerstack:getSourcePartnerstack", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePartnerstack.
 */
export interface GetSourcePartnerstackOutputArgs {
    sourceId: pulumi.Input<string>;
}
