// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSourceLooker(args: GetSourceLookerArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceLookerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceLooker:getSourceLooker", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceLooker.
 */
export interface GetSourceLookerArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceLooker.
 */
export interface GetSourceLookerResult {
    readonly configuration: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceLookerOutput(args: GetSourceLookerOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceLookerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceLooker:getSourceLooker", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceLooker.
 */
export interface GetSourceLookerOutputArgs {
    sourceId: pulumi.Input<string>;
}
