// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceRingcentral(args: GetSourceRingcentralArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceRingcentralResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceRingcentral:getSourceRingcentral", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceRingcentral.
 */
export interface GetSourceRingcentralArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceRingcentral.
 */
export interface GetSourceRingcentralResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceRingcentralResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceRingcentralOutput(args: GetSourceRingcentralOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceRingcentralResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceRingcentral:getSourceRingcentral", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceRingcentral.
 */
export interface GetSourceRingcentralOutputArgs {
    sourceId: pulumi.Input<string>;
}
