// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceTimely(args: GetSourceTimelyArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceTimelyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceTimely:getSourceTimely", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceTimely.
 */
export interface GetSourceTimelyArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceTimely.
 */
export interface GetSourceTimelyResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceTimelyResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceTimelyOutput(args: GetSourceTimelyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceTimelyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceTimely:getSourceTimely", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceTimely.
 */
export interface GetSourceTimelyOutputArgs {
    sourceId: pulumi.Input<string>;
}
