// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceEConomic(args: GetSourceEConomicArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceEConomicResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceEConomic:getSourceEConomic", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceEConomic.
 */
export interface GetSourceEConomicArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceEConomic.
 */
export interface GetSourceEConomicResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceEConomicResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceEConomicOutput(args: GetSourceEConomicOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceEConomicResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceEConomic:getSourceEConomic", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceEConomic.
 */
export interface GetSourceEConomicOutputArgs {
    sourceId: pulumi.Input<string>;
}
