// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceReferralhero(args: GetSourceReferralheroArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceReferralheroResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceReferralhero:getSourceReferralhero", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceReferralhero.
 */
export interface GetSourceReferralheroArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceReferralhero.
 */
export interface GetSourceReferralheroResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceReferralheroResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceReferralheroOutput(args: GetSourceReferralheroOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceReferralheroResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceReferralhero:getSourceReferralhero", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceReferralhero.
 */
export interface GetSourceReferralheroOutputArgs {
    sourceId: pulumi.Input<string>;
}
