// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceXsolla(args: GetSourceXsollaArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceXsollaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceXsolla:getSourceXsolla", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceXsolla.
 */
export interface GetSourceXsollaArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceXsolla.
 */
export interface GetSourceXsollaResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceXsollaResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceXsollaOutput(args: GetSourceXsollaOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceXsollaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceXsolla:getSourceXsolla", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceXsolla.
 */
export interface GetSourceXsollaOutputArgs {
    sourceId: pulumi.Input<string>;
}
