// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceInsightly(args: GetSourceInsightlyArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceInsightlyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceInsightly:getSourceInsightly", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceInsightly.
 */
export interface GetSourceInsightlyArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceInsightly.
 */
export interface GetSourceInsightlyResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceInsightlyResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceInsightlyOutput(args: GetSourceInsightlyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceInsightlyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceInsightly:getSourceInsightly", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceInsightly.
 */
export interface GetSourceInsightlyOutputArgs {
    sourceId: pulumi.Input<string>;
}
