// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourcePlanhat(args: GetSourcePlanhatArgs, opts?: pulumi.InvokeOptions): Promise<GetSourcePlanhatResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourcePlanhat:getSourcePlanhat", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePlanhat.
 */
export interface GetSourcePlanhatArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourcePlanhat.
 */
export interface GetSourcePlanhatResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourcePlanhatResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourcePlanhatOutput(args: GetSourcePlanhatOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourcePlanhatResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourcePlanhat:getSourcePlanhat", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePlanhat.
 */
export interface GetSourcePlanhatOutputArgs {
    sourceId: pulumi.Input<string>;
}
