// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceEverhour(args: GetSourceEverhourArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceEverhourResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceEverhour:getSourceEverhour", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceEverhour.
 */
export interface GetSourceEverhourArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceEverhour.
 */
export interface GetSourceEverhourResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceEverhourResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceEverhourOutput(args: GetSourceEverhourOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceEverhourResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceEverhour:getSourceEverhour", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceEverhour.
 */
export interface GetSourceEverhourOutputArgs {
    sourceId: pulumi.Input<string>;
}
