// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceChargify(args: GetSourceChargifyArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceChargifyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceChargify:getSourceChargify", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceChargify.
 */
export interface GetSourceChargifyArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceChargify.
 */
export interface GetSourceChargifyResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceChargifyResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceChargifyOutput(args: GetSourceChargifyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceChargifyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceChargify:getSourceChargify", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceChargify.
 */
export interface GetSourceChargifyOutputArgs {
    sourceId: pulumi.Input<string>;
}
