// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceSegment(args: GetSourceSegmentArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSegmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSegment:getSourceSegment", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSegment.
 */
export interface GetSourceSegmentArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSegment.
 */
export interface GetSourceSegmentResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceSegmentResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceSegmentOutput(args: GetSourceSegmentOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceSegmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceSegment:getSourceSegment", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSegment.
 */
export interface GetSourceSegmentOutputArgs {
    sourceId: pulumi.Input<string>;
}
