// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceAlgolia(args: GetSourceAlgoliaArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceAlgoliaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceAlgolia:getSourceAlgolia", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceAlgolia.
 */
export interface GetSourceAlgoliaArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceAlgolia.
 */
export interface GetSourceAlgoliaResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceAlgoliaResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceAlgoliaOutput(args: GetSourceAlgoliaOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceAlgoliaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceAlgolia:getSourceAlgolia", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceAlgolia.
 */
export interface GetSourceAlgoliaOutputArgs {
    sourceId: pulumi.Input<string>;
}
