// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceAviationstack(args: GetSourceAviationstackArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceAviationstackResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceAviationstack:getSourceAviationstack", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceAviationstack.
 */
export interface GetSourceAviationstackArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceAviationstack.
 */
export interface GetSourceAviationstackResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceAviationstackResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceAviationstackOutput(args: GetSourceAviationstackOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceAviationstackResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceAviationstack:getSourceAviationstack", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceAviationstack.
 */
export interface GetSourceAviationstackOutputArgs {
    sourceId: pulumi.Input<string>;
}
