// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceZohoInventory(args: GetSourceZohoInventoryArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceZohoInventoryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceZohoInventory:getSourceZohoInventory", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceZohoInventory.
 */
export interface GetSourceZohoInventoryArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceZohoInventory.
 */
export interface GetSourceZohoInventoryResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceZohoInventoryResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceZohoInventoryOutput(args: GetSourceZohoInventoryOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceZohoInventoryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceZohoInventory:getSourceZohoInventory", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceZohoInventory.
 */
export interface GetSourceZohoInventoryOutputArgs {
    sourceId: pulumi.Input<string>;
}
