// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourcePrimetric(args: GetSourcePrimetricArgs, opts?: pulumi.InvokeOptions): Promise<GetSourcePrimetricResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourcePrimetric:getSourcePrimetric", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePrimetric.
 */
export interface GetSourcePrimetricArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourcePrimetric.
 */
export interface GetSourcePrimetricResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourcePrimetricResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourcePrimetricOutput(args: GetSourcePrimetricOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourcePrimetricResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourcePrimetric:getSourcePrimetric", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePrimetric.
 */
export interface GetSourcePrimetricOutputArgs {
    sourceId: pulumi.Input<string>;
}
