// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceCaptainData(args: GetSourceCaptainDataArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceCaptainDataResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceCaptainData:getSourceCaptainData", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCaptainData.
 */
export interface GetSourceCaptainDataArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceCaptainData.
 */
export interface GetSourceCaptainDataResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceCaptainDataResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceCaptainDataOutput(args: GetSourceCaptainDataOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceCaptainDataResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceCaptainData:getSourceCaptainData", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceCaptainData.
 */
export interface GetSourceCaptainDataOutputArgs {
    sourceId: pulumi.Input<string>;
}
