// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceSentry(args: GetSourceSentryArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceSentryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceSentry:getSourceSentry", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSentry.
 */
export interface GetSourceSentryArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceSentry.
 */
export interface GetSourceSentryResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceSentryResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceSentryOutput(args: GetSourceSentryOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceSentryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceSentry:getSourceSentry", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceSentry.
 */
export interface GetSourceSentryOutputArgs {
    sourceId: pulumi.Input<string>;
}
