// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceAkeneo(args: GetSourceAkeneoArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceAkeneoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceAkeneo:getSourceAkeneo", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceAkeneo.
 */
export interface GetSourceAkeneoArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceAkeneo.
 */
export interface GetSourceAkeneoResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceAkeneoResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceAkeneoOutput(args: GetSourceAkeneoOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceAkeneoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceAkeneo:getSourceAkeneo", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceAkeneo.
 */
export interface GetSourceAkeneoOutputArgs {
    sourceId: pulumi.Input<string>;
}
