// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceYahooFinancePrice(args: GetSourceYahooFinancePriceArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceYahooFinancePriceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceYahooFinancePrice:getSourceYahooFinancePrice", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceYahooFinancePrice.
 */
export interface GetSourceYahooFinancePriceArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceYahooFinancePrice.
 */
export interface GetSourceYahooFinancePriceResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceYahooFinancePriceResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceYahooFinancePriceOutput(args: GetSourceYahooFinancePriceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceYahooFinancePriceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceYahooFinancePrice:getSourceYahooFinancePrice", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceYahooFinancePrice.
 */
export interface GetSourceYahooFinancePriceOutputArgs {
    sourceId: pulumi.Input<string>;
}
