// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceZapierSupportedStorage(args: GetSourceZapierSupportedStorageArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceZapierSupportedStorageResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceZapierSupportedStorage:getSourceZapierSupportedStorage", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceZapierSupportedStorage.
 */
export interface GetSourceZapierSupportedStorageArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceZapierSupportedStorage.
 */
export interface GetSourceZapierSupportedStorageResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceZapierSupportedStorageResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceZapierSupportedStorageOutput(args: GetSourceZapierSupportedStorageOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceZapierSupportedStorageResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceZapierSupportedStorage:getSourceZapierSupportedStorage", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceZapierSupportedStorage.
 */
export interface GetSourceZapierSupportedStorageOutputArgs {
    sourceId: pulumi.Input<string>;
}
