// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceGcs(args: GetSourceGcsArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceGcsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceGcs:getSourceGcs", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGcs.
 */
export interface GetSourceGcsArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceGcs.
 */
export interface GetSourceGcsResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceGcsResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceGcsOutput(args: GetSourceGcsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceGcsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceGcs:getSourceGcs", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGcs.
 */
export interface GetSourceGcsOutputArgs {
    sourceId: pulumi.Input<string>;
}
