// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceIterable(args: GetSourceIterableArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceIterableResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceIterable:getSourceIterable", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceIterable.
 */
export interface GetSourceIterableArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceIterable.
 */
export interface GetSourceIterableResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceIterableResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceIterableOutput(args: GetSourceIterableOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceIterableResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceIterable:getSourceIterable", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceIterable.
 */
export interface GetSourceIterableOutputArgs {
    sourceId: pulumi.Input<string>;
}
