// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceMssql(args: GetSourceMssqlArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceMssqlResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceMssql:getSourceMssql", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceMssql.
 */
export interface GetSourceMssqlArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceMssql.
 */
export interface GetSourceMssqlResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceMssqlResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceMssqlOutput(args: GetSourceMssqlOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceMssqlResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceMssql:getSourceMssql", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceMssql.
 */
export interface GetSourceMssqlOutputArgs {
    sourceId: pulumi.Input<string>;
}
