// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceEventbrite(args: GetSourceEventbriteArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceEventbriteResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceEventbrite:getSourceEventbrite", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceEventbrite.
 */
export interface GetSourceEventbriteArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceEventbrite.
 */
export interface GetSourceEventbriteResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceEventbriteResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceEventbriteOutput(args: GetSourceEventbriteOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceEventbriteResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceEventbrite:getSourceEventbrite", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceEventbrite.
 */
export interface GetSourceEventbriteOutputArgs {
    sourceId: pulumi.Input<string>;
}
