// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourcePoplar(args: GetSourcePoplarArgs, opts?: pulumi.InvokeOptions): Promise<GetSourcePoplarResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourcePoplar:getSourcePoplar", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePoplar.
 */
export interface GetSourcePoplarArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourcePoplar.
 */
export interface GetSourcePoplarResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourcePoplarResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourcePoplarOutput(args: GetSourcePoplarOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourcePoplarResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourcePoplar:getSourcePoplar", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePoplar.
 */
export interface GetSourcePoplarOutputArgs {
    sourceId: pulumi.Input<string>;
}
