// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceThriveLearning(args: GetSourceThriveLearningArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceThriveLearningResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceThriveLearning:getSourceThriveLearning", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceThriveLearning.
 */
export interface GetSourceThriveLearningArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceThriveLearning.
 */
export interface GetSourceThriveLearningResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceThriveLearningResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceThriveLearningOutput(args: GetSourceThriveLearningOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceThriveLearningResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceThriveLearning:getSourceThriveLearning", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceThriveLearning.
 */
export interface GetSourceThriveLearningOutputArgs {
    sourceId: pulumi.Input<string>;
}
