// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceOpenExchangeRates(args: GetSourceOpenExchangeRatesArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceOpenExchangeRatesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceOpenExchangeRates:getSourceOpenExchangeRates", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceOpenExchangeRates.
 */
export interface GetSourceOpenExchangeRatesArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceOpenExchangeRates.
 */
export interface GetSourceOpenExchangeRatesResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceOpenExchangeRatesResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceOpenExchangeRatesOutput(args: GetSourceOpenExchangeRatesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceOpenExchangeRatesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceOpenExchangeRates:getSourceOpenExchangeRates", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceOpenExchangeRates.
 */
export interface GetSourceOpenExchangeRatesOutputArgs {
    sourceId: pulumi.Input<string>;
}
