// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourcePersistiq(args: GetSourcePersistiqArgs, opts?: pulumi.InvokeOptions): Promise<GetSourcePersistiqResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourcePersistiq:getSourcePersistiq", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePersistiq.
 */
export interface GetSourcePersistiqArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourcePersistiq.
 */
export interface GetSourcePersistiqResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourcePersistiqResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourcePersistiqOutput(args: GetSourcePersistiqOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourcePersistiqResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourcePersistiq:getSourcePersistiq", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourcePersistiq.
 */
export interface GetSourcePersistiqOutputArgs {
    sourceId: pulumi.Input<string>;
}
