// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceStatuspage(args: GetSourceStatuspageArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceStatuspageResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceStatuspage:getSourceStatuspage", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceStatuspage.
 */
export interface GetSourceStatuspageArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceStatuspage.
 */
export interface GetSourceStatuspageResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceStatuspageResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceStatuspageOutput(args: GetSourceStatuspageOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceStatuspageResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceStatuspage:getSourceStatuspage", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceStatuspage.
 */
export interface GetSourceStatuspageOutputArgs {
    sourceId: pulumi.Input<string>;
}
