// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceGlassfrog(args: GetSourceGlassfrogArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceGlassfrogResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceGlassfrog:getSourceGlassfrog", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGlassfrog.
 */
export interface GetSourceGlassfrogArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceGlassfrog.
 */
export interface GetSourceGlassfrogResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceGlassfrogResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceGlassfrogOutput(args: GetSourceGlassfrogOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceGlassfrogResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceGlassfrog:getSourceGlassfrog", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceGlassfrog.
 */
export interface GetSourceGlassfrogOutputArgs {
    sourceId: pulumi.Input<string>;
}
