// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSourceFreshchat(args: GetSourceFreshchatArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceFreshchatResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("airbyte:index/getSourceFreshchat:getSourceFreshchat", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceFreshchat.
 */
export interface GetSourceFreshchatArgs {
    sourceId: string;
}

/**
 * A collection of values returned by getSourceFreshchat.
 */
export interface GetSourceFreshchatResult {
    readonly configuration: string;
    readonly createdAt: number;
    readonly definitionId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resourceAllocation: outputs.GetSourceFreshchatResourceAllocation;
    readonly sourceId: string;
    readonly sourceType: string;
    readonly workspaceId: string;
}
export function getSourceFreshchatOutput(args: GetSourceFreshchatOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceFreshchatResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("airbyte:index/getSourceFreshchat:getSourceFreshchat", {
        "sourceId": args.sourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSourceFreshchat.
 */
export interface GetSourceFreshchatOutputArgs {
    sourceId: pulumi.Input<string>;
}
